language: python

services:
  - docker

jobs:
  include:
    - stage: Testing
      env: SUPPORTED_PG_VERSIONS=9.5.13
      script: sudo make test

    - stage: # Intentionally left blank to parallelize
      env: SUPPORTED_PG_VERSIONS=9.6.4
      script: sudo make test

    - stage: # Intentionally left blank to parallelize
      env: SUPPORTED_PG_VERSIONS=10.4
      script: sudo make test

    - stage: # Intentionally left blank to parallelize
      install: pip install -e . -r requirements-docs.txt
      script: make docs
